create table if not exists public.jobs (
    id bigint generated by default as identity primary key,
    company_name varchar(255),
    job_title varchar(255),
    city varchar(120),
    platform varchar(120),
    job_link text,
    salary_text varchar(120),
    salary_min integer,
    salary_max integer,
    experience_required varchar(120),
    degree_required varchar(120),
    remote_allowed boolean not null default false,
    jd_raw_text text,
    skills_extracted text[] not null default array[]::text[],
    keywords text[] not null default array[]::text[],
    track varchar(64) not null default 'other',
    match_score integer not null default 0,
    match_level varchar(64) not null default 'ignore',
    status varchar(64) not null default 'pending_analysis',
    resume_version varchar(120),
    notes text,
    created_at timestamp not null default timezone('utc', now()),
    updated_at timestamp not null default timezone('utc', now())
);

create table if not exists public.app_preferences (
    id integer primary key default 1 check (id = 1),
    target_cities text[] not null default array[]::text[],
    target_tracks text[] not null default array[]::text[],
    priority_skills text[] not null default array[]::text[],
    min_salary integer,
    default_resume_version varchar(120),
    llm_enabled boolean not null default false,
    created_at timestamp not null default timezone('utc', now()),
    updated_at timestamp not null default timezone('utc', now())
);

create table if not exists public.source_links (
    id bigint generated by default as identity primary key,
    source_key varchar(80) not null unique,
    platform_name varchar(120) not null,
    title varchar(180) not null,
    url text not null,
    city varchar(120),
    track varchar(64),
    keywords text[] not null default array[]::text[],
    enabled boolean not null default true,
    sort_order integer not null default 100,
    created_at timestamp not null default timezone('utc', now()),
    updated_at timestamp not null default timezone('utc', now())
);

create table if not exists public.job_events (
    id bigint generated by default as identity primary key,
    job_id bigint not null references public.jobs(id) on delete cascade,
    event_type varchar(64) not null,
    notes text,
    event_at timestamp not null default timezone('utc', now()),
    created_at timestamp not null default timezone('utc', now())
);

create index if not exists idx_job_events_job_id_event_at
    on public.job_events (job_id, event_at desc);

alter table public.jobs enable row level security;
alter table public.app_preferences enable row level security;
alter table public.source_links enable row level security;
alter table public.job_events enable row level security;

drop policy if exists "jobs_read_all" on public.jobs;
create policy "jobs_read_all"
    on public.jobs
    for select
    to anon, authenticated
    using (true);

drop policy if exists "jobs_write_all" on public.jobs;
create policy "jobs_write_all"
    on public.jobs
    for all
    to anon, authenticated
    using (true)
    with check (true);

drop policy if exists "preferences_read_all" on public.app_preferences;
create policy "preferences_read_all"
    on public.app_preferences
    for select
    to anon, authenticated
    using (true);

drop policy if exists "preferences_write_all" on public.app_preferences;
create policy "preferences_write_all"
    on public.app_preferences
    for all
    to anon, authenticated
    using (true)
    with check (true);

drop policy if exists "source_links_read_all" on public.source_links;
create policy "source_links_read_all"
    on public.source_links
    for select
    to anon, authenticated
    using (true);

drop policy if exists "source_links_write_all" on public.source_links;
create policy "source_links_write_all"
    on public.source_links
    for all
    to anon, authenticated
    using (true)
    with check (true);

drop policy if exists "job_events_read_all" on public.job_events;
create policy "job_events_read_all"
    on public.job_events
    for select
    to anon, authenticated
    using (true);

drop policy if exists "job_events_write_all" on public.job_events;
create policy "job_events_write_all"
    on public.job_events
    for all
    to anon, authenticated
    using (true)
    with check (true);

insert into public.app_preferences (
    id,
    target_cities,
    target_tracks,
    priority_skills,
    min_salary,
    default_resume_version,
    llm_enabled
) values (
    1,
    array['上海', '远程']::text[],
    array['data_analyst', 'ai_app_dev', 'android_client', 'model_deployment']::text[],
    array['Python', 'SQL', 'LLM', 'RAG', 'Agent', 'Docker', 'Linux']::text[],
    18,
    'v1',
    false
) on conflict (id) do nothing;

insert into public.source_links (
    source_key,
    platform_name,
    title,
    url,
    city,
    track,
    keywords,
    enabled,
    sort_order
) values
    ('boss_zhipin', 'BOSS直聘', 'BOSS直聘职位搜索', 'https://www.zhipin.com/', null, null, array['AI', '数据分析', 'Python']::text[], true, 10),
    ('lagou', '拉勾', '拉勾互联网招聘', 'https://www.lagou.com/', null, null, array['互联网', 'AI', '数据']::text[], true, 20),
    ('liepin', '猎聘', '猎聘中高端职位', 'https://www.liepin.com/', null, null, array['中高端', 'AI', '技术']::text[], true, 30),
    ('zhaopin', '智联招聘', '智联招聘职位分类', 'https://www.zhaopin.com/jobs/', null, null, array['社招', '技术']::text[], true, 40),
    ('51job', '前程无忧', '前程无忧职位搜索', 'https://www.51job.com/', null, null, array['社招', '上海']::text[], true, 50),
    ('nowcoder', '牛客', '牛客求职职位', 'https://www.nowcoder.com/jobs/school/jobs', null, null, array['校招', '实习', '技术']::text[], true, 60),
    ('maimai', '脉脉', '脉脉职场机会', 'https://maimai.cn/', null, null, array['内推', '职场', 'AI']::text[], true, 70)
on conflict (source_key) do nothing;

