CREATE TABLE IF NOT EXISTS jobs (
    id SERIAL PRIMARY KEY,
    company_name VARCHAR(255),
    job_title VARCHAR(255),
    city VARCHAR(120),
    platform VARCHAR(120),
    job_link TEXT,
    salary_text VARCHAR(120),
    salary_min INTEGER,
    salary_max INTEGER,
    experience_required VARCHAR(120),
    degree_required VARCHAR(120),
    remote_allowed BOOLEAN NOT NULL DEFAULT FALSE,
    jd_raw_text TEXT,
    skills_extracted TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    keywords TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    track VARCHAR(64) NOT NULL DEFAULT 'other',
    match_score INTEGER NOT NULL DEFAULT 0,
    match_level VARCHAR(64) NOT NULL DEFAULT 'ignore',
    status VARCHAR(64) NOT NULL DEFAULT 'pending_analysis',
    resume_version VARCHAR(120),
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
